spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop; # MVCC=TRUE # h2 DB 접근하는 곳 경로
    # MVCC=TRUE 넣어주는것 권장, 이것 넣어주면 여러 db에 한번에 접근시 더빠름
    # MVCC 옵션은 1.4.198버전부터 제거가 되었으니 1.4.200 버전에서 사용시 오류남
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 실행시점에 내가 가지고 있는 entity 다 지우고 다시 생성
    properties:
      hibernate:
#        show_sql: true # System.out에 하이버네이트 실행 SQL 남김
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # logger를 통해 하이버네이트 실행 SQL을 남김
    # 하이버네이트가 남기는 모든 로그가 debug모드로
    org.hibernate.type: trace #SQL 실행 파라미터를 로그로 남긴다

